name: Rust

on: 
  push:
    tags:
    - '*'



env:
  CARGO_TERM_COLOR: always

jobs:
  # build-static:
  
  #   runs-on: ubuntu-latest

  #   permissions:
  #     contents: write

  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: Install dependencies
  #     run: sudo apt update && sudo apt install -y clang cmake libevent-dev libclang-dev libcurl4-openssl-dev curl
  #   - run: rustup toolchain install stable --profile minimal
  #   - uses: Swatinem/rust-cache@v2
  #   - uses: actions-rs/toolchain@v1
  #     with:
  #       toolchain: stable
  #       target: x86_64-unknown-linux-musl
  #       override: true
  #   - uses: actions-rs/cargo@v1
  #     with:
  #       use-cross: true
  #       command: build
  #       args: --target x86_64-unknown-linux-musl
  #   - name: rename build
  #     run: cp target/x86_64-unknown-linux-musl/release/torexpo target/x86_64-unknown-linux-musl/release/torexpo-static
  #   - name: Release
  #     uses: softprops/action-gh-release@v1
  #     if: startsWith(github.ref, 'refs/tags/')
  #     with:
  #       files: target/x86_64-unknown-linux-musl/release/torexpo-static
  
  build:
  
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt update && sudo apt install -y clang cmake libevent-dev libclang-dev libcurl4-openssl-dev curl
    - run: rustup toolchain install stable --profile minimal
    - uses: Swatinem/rust-cache@v2
    - name: Build
      run: cargo build --release
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: target/release/torexpo